version: '3'

services:
  data-receiver:
    container_name: data-receiver
    build: collectord/data-receiver/
    ports:
      - "5555:5555"

# Golang backend
# Elm frontend
# no need to build in the container
# just give the binary to the container
# and the main.js
  local-webserver:
    container_name: local-webserver
    build: collectord/local-webserver
    ports:
      - "9999:9999"

# ASH collector requires access to the SQLite database
# which is in the home directory .ash
  ash-collector-daemon:
    container_name: ash-collector-daemon
    build: collectors/ash-collector
    network_mode: "host"
    volumes:
      - /home/steve/.ash:/ash

  firefox-collector-daemon:
    container_name: firefox-collector-daemon
    build: collectors/firefox-collector
    network_mode: "host"
    volumes:
      - /home/steve/.mozilla:/home/steve/.mozilla
